 1: Load the Dataset

# New Section

In [6]:
import pandas as pd

# Load the dirty dataset
df = pd.read_csv('movie_dataset_dirty.csv', on_bad_lines='skip', engine='python')
# Show initial data
print("Initial shape:", df.shape)
df.head()

Initial shape: (5043, 24)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0.0,237000000.0,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995.0,culture clash future space war space colony so...,en,avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,NaN,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",NaN
1,NaN,NaN,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285.0,ocean drug abuse exotic island east india tr...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""english""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500.0,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2.0,245000000.0,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647.0,NaN,en,spectre,A cryptic message from Bond’s past sends him o...,NaN,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""fran\u00e7ais""...",Released,A Plan No One Escapes,spectre,6.3,4466.0,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3.0,250000000.0,NaN,http://www.thedarkknightrises.com/,NaN,dc comics crime fighter terrorist secret ident...,en,the dark knight rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",released,The Legend Ends,the dark knight rises,7.6,9106.0,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'hans zimmer', 'gender': 2, 'depar...",christopher nolan
4,4.0,260000000.0,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529.0,based on novel mars medallion space travel p...,en,John Carter,"john carter is a war-weary, former military ...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",NaN,NaN,john carter,6.1,2124.0,taylor kitsch lynn collins samantha morton w...,"[{'name': 'andrew stanton', 'gender': 2, 'de...",NaN

2: Remove Duplicates

In [7]:
# Remove duplicate rows
df = df.drop_duplicates()

print("After removing duplicates:", df.shape)
df.head()

After removing duplicates: (5042, 24)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0.0,237000000.0,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995.0,culture clash future space war space colony so...,en,avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,NaN,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",NaN
1,NaN,NaN,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285.0,ocean drug abuse exotic island east india tr...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""english""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500.0,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2.0,245000000.0,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647.0,NaN,en,spectre,A cryptic message from Bond’s past sends him o...,NaN,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""fran\u00e7ais""...",Released,A Plan No One Escapes,spectre,6.3,4466.0,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3.0,250000000.0,NaN,http://www.thedarkknightrises.com/,NaN,dc comics crime fighter terrorist secret ident...,en,the dark knight rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",released,The Legend Ends,the dark knight rises,7.6,9106.0,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'hans zimmer', 'gender': 2, 'depar...",christopher nolan
4,4.0,260000000.0,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529.0,based on novel mars medallion space travel p...,en,John Carter,"john carter is a war-weary, former military ...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",NaN,NaN,john carter,6.1,2124.0,taylor kitsch lynn collins samantha morton w...,"[{'name': 'andrew stanton', 'gender': 2, 'de...",NaN

3: Strip Whitespace & Normalize Text

In [8]:
# Strip whitespaces and convert to title case
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype(str).str.strip().str.title()

df.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0.0,237000000.0,Action Adventure Fantasy Science Fiction,Http://Www.Avatarmovie.Com/,19995.0,Culture Clash Future Space War Space Colony So...,En,Avatar,"In The 22Nd Century, A Paraplegic Marine Is Di...",150.437577,...,162.0,"[{""Iso_639_1"": ""En"", ""Name"": ""English""}, {""Iso...",Released,Enter The World Of Pandora.,Avatar,7.2,NaN,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'Name': 'Stephen E. Rivkin', 'Gender': 0, 'D...",Nan
1,NaN,NaN,Adventure Fantasy Action,Http://Disney.Go.Com/Disneypictures/Pirates/,285.0,Ocean Drug Abuse Exotic Island East India Trad...,En,Pirates Of The Caribbean: At World'S End,"Captain Barbossa, Long Believed To Be Dead, Ha...",139.082615,...,169.0,"[{""Iso_639_1"": ""En"", ""Name"": ""English""}]",Released,"At The End Of The World, The Adventure Begins.",Pirates Of The Caribbean: At World'S End,6.9,4500.0,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'Name': 'Dariusz Wolski', 'Gender': 2, 'Depa...",Gore Verbinski
2,2.0,245000000.0,Action Adventure Crime,Http://Www.Sonypictures.Com/Movies/Spectre/,206647.0,Nan,En,Spectre,A Cryptic Message From Bond’S Past Sends Him O...,NaN,...,148.0,"[{""Iso_639_1"": ""Fr"", ""Name"": ""Fran\U00E7Ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466.0,Daniel Craig Christoph Waltz L\U00E9A Seydoux ...,"[{'Name': 'Thomas Newman', 'Gender': 2, 'Depar...",Sam Mendes
3,3.0,250000000.0,Nan,Http://Www.Thedarkknightrises.Com/,NaN,Dc Comics Crime Fighter Terrorist Secret Ident...,En,The Dark Knight Rises,Following The Death Of District Attorney Harve...,112.312950,...,165.0,"[{""Iso_639_1"": ""En"", ""Name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106.0,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'Name': 'Hans Zimmer', 'Gender': 2, 'Departm...",Christopher Nolan
4,4.0,260000000.0,Action Adventure Science Fiction,Http://Movies.Disney.Com/John-Carter,49529.0,Based On Novel Mars Medallion Space Travel Pri...,En,John Carter,"John Carter Is A War-Weary, Former Military Ca...",43.926995,...,132.0,"[{""Iso_639_1"": ""En"", ""Name"": ""English""}]",Nan,Nan,John Carter,6.1,2124.0,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'Name': 'Andrew Stanton', 'Gender': 2, 'Depa...",Nan

Cell 4: Handle Missing Values

In [9]:
# Drop rows with any missing values
df = df.dropna()

print("After dropping missing values:", df.shape)
df.head()

After dropping missing values: (2121, 24)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
4,4.0,260000000.0,Action Adventure Science Fiction,Http://Movies.Disney.Com/John-Carter,49529.0,Based On Novel Mars Medallion Space Travel Pri...,En,John Carter,"John Carter Is A War-Weary, Former Military Ca...",43.926995,...,132.0,"[{""Iso_639_1"": ""En"", ""Name"": ""English""}]",Nan,Nan,John Carter,6.1,2124.0,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'Name': 'Andrew Stanton', 'Gender': 2, 'Depa...",Nan
5,5.0,258000000.0,Fantasy Action Adventure,Http://Www.Sonypictures.Com/Movies/Spider-Man3/,559.0,Dual Identity Amnesia Sandstorm Love Of One'S ...,En,Spider-Man 3,The Seemingly Invincible Spider-Man Goes Up Ag...,115.699814,...,139.0,"[{""Iso_639_1"": ""En"", ""Name"": ""English""}, {""Iso...",Nan,The Battle Within.,Spider-Man 3,5.9,3576.0,Nan,"[{'Name': 'Francine Maisler', 'Gender': 1, 'De...",Sam Raimi
8,8.0,250000000.0,Adventure Fantasy Family,Http://Harrypotter.Warnerbros.Com/Harrypottera...,767.0,Witch Magic Broom School Of Witchcraft Wizardry,Nan,Harry Potter And The Half-Blood Prince,"As Harry Begins His Sixth Year At Hogwarts, He...",98.885637,...,153.0,"[{""Iso_639_1"": ""En"", ""Name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter And The Half-Blood Prince,7.4,5293.0,Daniel Radcliffe Rupert Grint Emma Watson Tom ...,"[{'Name': 'Bruno Delbonnel', 'Gender': 0, 'Dep...",David Yates
10,10.0,270000000.0,Adventure Fantasy Action Science Fiction,Http://Www.Superman.Com,1452.0,Saving The World Dc Comics Invulnerability Seq...,En,Superman Returns,Superman Returns To Discover His 5-Year Absenc...,57.925623,...,154.0,Nan,Released,Nan,Superman Returns,5.4,1400.0,Brandon Routh Kevin Spacey Kate Bosworth James...,"[{'Name': 'Roger Mussenden', 'Gender': 2, 'Dep...",Bryan Singer
17,17.0,380000000.0,Adventure Action Fantasy,Http://Disney.Go.Com/Pirates/Index-On-Stranger...,1865.0,Sea Captain Mutiny Sword Prime Minister,En,Pirates Of The Caribbean: On Stranger Tides,Captain Jack Sparrow Crosses Paths With A Woma...,135.413856,...,136.0,"[{""Iso_639_1"": ""En"", ""Name"": ""English""}, {""Iso...",Released,Live Forever Or Die Trying.,Nan,6.4,4948.0,Johnny Depp Pen\U00E9Lope Cruz Ian Mcshane Kev...,"[{'Name': 'Dariusz Wolski', 'Gender': 2, 'Depa...",Rob Marshall

5: Save the Cleaned Dataset

In [10]:
# Save the cleaned dataset
df.to_csv('movie_dataset_cleaned.csv', index=False)
print("Cleaned dataset saved as 'movie_dataset_cleaned.csv'")

Cleaned dataset saved as 'movie_dataset_cleaned.csv'